In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
import io
uploaded = files.upload()
Orders = pd.read_csv(io.BytesIO(uploaded[list(uploaded.keys())[0]]))
Orders.head()

Saving olist_orders_dataset. (3)csv.csv to olist_orders_dataset. (3)csv (3).csv

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [ ]:
print(Orders.shape)
print(Orders.columns)
print(Orders.isnull().sum())
print(Orders.duplicated().sum())

(99441, 8)
Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
0

In [ ]:
print(Orders.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB
None

In [ ]:
Orders['order_id'].nunique()

99441

In [ ]:
uploaded = files.upload()
Customers = pd.read_csv(io.BytesIO(uploaded['olist_customers_dataset.csv']))
Customers.head()

Saving olist_customers_dataset.csv to olist_customers_dataset.csv

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [ ]:
print(Customers.shape)
print(Customers.columns)
print(Customers.isnull().sum())
print(Customers.duplicated().sum())

(99441, 5)
Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
0

In [ ]:
Customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [ ]:
Customers['customer_id'].nunique()

99441

In [ ]:
Customers['customer_unique_id'].nunique()

96096

In [ ]:
uploaded = files.upload()
Orders_item = pd.read_csv(io.BytesIO(uploaded['olist_order_items_dataset.csv']))
Orders_item.head()

Saving olist_order_items_dataset.csv to olist_order_items_dataset.csv

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [ ]:
print(Orders_item.shape)
print(Orders_item.columns)
print(Orders_item.isnull().sum())
print(Orders_item.duplicated().sum())

(112650, 7)
Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
0

In [ ]:
Orders_item['order_id'].nunique()

98666

In [ ]:
Orders_item['product_id'].nunique()

32951

In [ ]:
Orders_item['seller_id'].nunique()

3095

In [ ]:
Orders_item.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [ ]:
uploaded = files.upload()
Orders_pay = pd.read_csv(io.BytesIO(uploaded['olist_order_payments_dataset.csv']))
Orders_pay.head()

Saving olist_order_payments_dataset.csv to olist_order_payments_dataset.csv

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [ ]:
print(Orders_pay.shape)
print(Orders_pay.columns)
print(Orders_pay.isnull().sum())
print(Orders_pay.duplicated().sum())

(103886, 5)
Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
0

In [ ]:
Orders_pay.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [ ]:
print(Orders_pay['order_id'].nunique())
print(Orders_pay['payment_type'].nunique())

99440
5

In [ ]:
uploaded = files.upload()
Products = pd.read_csv(io.BytesIO(uploaded['olist_products_dataset.csv']))
Products.head()

Saving olist_products_dataset.csv to olist_products_dataset.csv

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [ ]:
print(Products.shape)
print(Products.columns)
print(Products.isnull().sum())
print(Products.duplicated().sum())

(32951, 9)
Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
0

In [ ]:
Products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [ ]:
Products[
      Products['product_category_name'].isnull()
      ].isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                1
product_length_cm               1
product_height_cm               1
product_width_cm                1
dtype: int64

In [ ]:
Products['product_category_name'].nunique()

73

In [ ]:
uploaded = files.upload()
Review = pd.read_csv(io.BytesIO(uploaded['olist_order_reviews_dataset.csv']))
Review.head()

Saving olist_order_reviews_dataset.csv to olist_order_reviews_dataset.csv

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [ ]:
print(Review.shape)
print(Review.columns)
print(Review.isnull().sum())
print(Review.duplicated().sum())

(99224, 7)
Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
0

In [ ]:
Review.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [ ]:
Review['order_id'].nunique()

98673

In [ ]:
Review['review_score'].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [ ]:
uploaded = files.upload()
Sellers = pd.read_csv(io.BytesIO(uploaded['olist_sellers_dataset.csv']))
Sellers.head()

Saving olist_sellers_dataset.csv to olist_sellers_dataset.csv

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [ ]:
print(Sellers.shape)
print(Sellers.columns)
print(Sellers.isnull().sum())
print(Sellers.duplicated().sum())

(3095, 4)
Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64
0

In [ ]:
Sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [ ]:
uploaded = files.upload()
Geolocation = pd.read_csv(io.BytesIO(uploaded['olist_geolocation_dataset.csv']))
Geolocation.head()

Saving olist_geolocation_dataset.csv to olist_geolocation_dataset.csv

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [ ]:
print(Geolocation.shape)
print(Geolocation.columns)
print(Geolocation.isnull().sum())
print(Geolocation.duplicated().sum())

(1000163, 5)
Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='object')
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64
261831

In [ ]:
Geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [ ]:
uploaded = files.upload()
Category_translation= pd.read_csv(io.BytesIO(uploaded['product_category_name_translation.csv']))
Category_translation.head()

Saving product_category_name_translation.csv to product_category_name_translation.csv

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [ ]:
print(Category_translation.shape)
print(Category_translation.columns)
print(Category_translation.isnull().sum())
print(Category_translation.duplicated().sum())

(71, 2)
Index(['product_category_name', 'product_category_name_english'], dtype='object')
product_category_name            0
product_category_name_english    0
dtype: int64
0

In [ ]:
Category_translation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

# **RELACTIONSHIP_CHECK**

In [ ]:
Orders['customer_id'].isin(
      Customers['customer_id']
      ).mean()

np.float64(1.0)

In [ ]:
Orders_item['order_id'].isin(
      Orders['order_id']
      ).mean()

np.float64(1.0)

In [ ]:
Orders_item['product_id'].isin(
      Products['product_id']
      ).mean()

np.float64(1.0)

In [ ]:
Orders_item['seller_id'].isin(
      Sellers['seller_id']
      ).mean()

np.float64(1.0)

In [ ]:
Review['order_id'].isin(
      Orders['order_id']
      ).mean()

np.float64(1.0)

# **DATA_CLEANING**

In [ ]:
Orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [ ]:
pd.crosstab(
      Orders['order_status'],
          Orders['order_delivered_customer_date'].isnull()
          )

order_delivered_customer_date  False  True
order_status
approved                           0      2
canceled                           6    619
created                            0      5
delivered                      96470      8
invoiced                           0    314
processing                         0    301
shipped                            0   1107
unavailable                        0    609

In [ ]:
Orders[
      (Orders['order_status'] == 'delivered') &
          (Orders['order_delivered_customer_date'].isnull())
          ]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaN,2017-12-18 00:00:00
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaN,2018-07-16 00:00:00
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaN,2018-07-24 00:00:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaN,NaN,2017-06-23 00:00:00
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaN,2018-06-26 00:00:00
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaN,2018-07-19 00:00:00

In [ ]:
Orders[
      (Orders['order_status'] == 'delivered') &
          (Orders['order_delivered_customer_date'].isnull())
          ].T

,3002,20618,43834,79263,82868,92643,97647,98038
order_id,2d1e2d5bf4dc7227b3bfebb81328c15f,f5dd62b788049ad9fc0526e3ad11a097,2ebdfc4f15f23b91474edf87475f108e,e69f75a717d64fc5ecdfae42b2e8e086,0d3268bad9b086af767785e3f0fc0133,2d858f451373b04fb5c984a1cc2defaf,ab7c89dc1bf4a1ead9d6ec1ec8968a84,20edc82cf5400ce95e1afacc25798b31
customer_id,ec05a6d8558c6455f0cbbd8a420ad34f,5e89028e024b381dc84a13a3570decb4,29f0540231702fda0cfdee0a310f11aa,cfda40ca8dd0a5d486a9635b611b398a,4f1d63d35fb7c8999853b2699f5c7649,e08caf668d499a6d643dafd7c5cc498a,dd1b84a7286eb4524d52af4256c0ba24,28c37425f1127d887d7337f284080a0f
order_status,delivered,delivered,delivered,delivered,delivered,delivered,delivered,delivered
order_purchase_timestamp,2017-11-28 17:44:07,2018-06-20 06:58:43,2018-07-01 17:05:11,2018-07-01 22:05:55,2018-07-01 21:14:02,2017-05-25 23:22:43,2018-06-08 12:09:39,2018-06-27 16:09:12
order_approved_at,2017-11-28 17:56:40,2018-06-20 07:19:05,2018-07-01 17:15:12,2018-07-01 22:15:14,2018-07-01 21:29:54,2017-05-25 23:30:16,2018-06-08 12:36:39,2018-06-27 16:29:30
order_delivered_carrier_date,2017-11-30 18:12:23,2018-06-25 08:05:00,2018-07-03 13:57:00,2018-07-03 13:57:00,2018-07-03 09:28:00,NaN,2018-06-12 14:10:00,2018-07-03 19:26:00
order_delivered_customer_date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_estimated_delivery_date,2017-12-18 00:00:00,2018-07-16 00:00:00,2018-07-30 00:00:00,2018-07-30 00:00:00,2018-07-24 00:00:00,2017-06-23 00:00:00,2018-06-26 00:00:00,2018-07-19 00:00:00

In [ ]:
order_date_cols = [
      'order_purchase_timestamp',
          'order_approved_at',
              'order_delivered_carrier_date',
                  'order_delivered_customer_date',
                      'order_estimated_delivery_date'
                      ]

for col in order_date_cols:
       Orders[col] = pd.to_datetime(Orders[col], errors='coerce')


Orders_pay['payment_value'] = pd.to_numeric(
Orders_pay['payment_value'],
errors='coerce'
)

Orders_item['shipping_limit_date'] = pd.to_datetime(
Orders_item['shipping_limit_date'],
errors='coerce'
)

In [ ]:
review_date_cols = [
      'review_creation_date',
          'review_answer_timestamp'
          ]

for col in review_date_cols:
         Review[col] = pd.to_datetime(
         Review[col],
         errors='coerce'
      )

In [ ]:
Orders.drop_duplicates(inplace=True)
Customers.drop_duplicates(inplace=True)
Orders_item.drop_duplicates(inplace=True)
Orders_pay.drop_duplicates(inplace=True)
Products.drop_duplicates(inplace=True)
Review.drop_duplicates(inplace=True)
Sellers.drop_duplicates(inplace=True)
Geolocation.drop_duplicates(inplace=True)
Category_translation.drop_duplicates(inplace=True)

In [ ]:
Products['product_category_name'] = (
      Products['product_category_name']
          .fillna('unknown')
          )

numeric_product_cols = [
'product_name_lenght',
'product_description_lenght',
'product_photos_qty',
'product_weight_g',
'product_length_cm',
'product_height_cm',
'product_width_cm'
]

for col in numeric_product_cols:
     Products[col] = Products[col].fillna(
     Products[col].median()
     )

In [ ]:
Review['review_comment_title'] = (
Review['review_comment_title'].fillna('')
      )

Review['review_comment_message'] = (
Review['review_comment_message'].fillna('')
      )

In [ ]:
Customers['customer_city'] = Customers['customer_city'].str.strip().str.lower()
Customers['customer_state'] = Customers['customer_state'].str.strip().str.upper()

Sellers['seller_city'] = Sellers['seller_city'].str.strip().str.lower()
Sellers['seller_state'] = Sellers['seller_state'].str.strip().str.upper()

Orders['order_status'] = Orders['order_status'].str.strip().str.lower()

Orders_pay['payment_type'] = Orders_pay['payment_type'].str.strip().str.lower()

In [ ]:
Orders['delivery_days'] = (
Orders['order_delivered_customer_date']
- Orders['order_purchase_timestamp']
).dt.total_seconds() / 86400

In [ ]:
Orders['delivery_delay_days'] = (
Orders['order_delivered_customer_date']
  - Orders['order_estimated_delivery_date']
   ).dt.total_seconds() / 86400

In [ ]:
Orders['is_late'] = (
      Orders['delivery_delay_days'] > 0)

In [ ]:
Orders['order_month'] = (
      Orders['order_purchase_timestamp']
          .dt.to_period('M')
              .astype(str)
              )

In [ ]:
Orders.to_csv('clean_Orders.csv', index=False)

Customers.to_csv('clean_Customers.csv', index=False)

Orders_item.to_csv('clean_Order_Items.csv', index=False)

Orders_pay.to_csv('clean_Payments.csv', index=False)

Products.to_csv('clean_Products.csv', index=False)

Review.to_csv('clean_Reviews.csv', index=False)

Sellers.to_csv('clean_Sellers.csv', index=False)

Geolocation.to_csv('clean_Geolocation.csv', index=False)

Category_translation.to_csv('clean_Category_Translation.csv', index=False)

In [ ]:
from google.colab import files
import io
uploaded = files.upload()
Orders = pd.read_csv(io.BytesIO(uploaded[list(uploaded.keys())[0]]))
Orders.head()

Saving clean_Orders.csv to clean_Orders (1).csv

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delivery_delay_days,is_late,order_month
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.436574,-7.107488,False,2017-10
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13.782037,-5.355729,False,2018-07
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9.394213,-17.245498,False,2018-08
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13.208750,-12.980069,False,2017-11
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2.873877,-9.238171,False,2018-02

In [ ]:
print(Orders.shape)
print(Orders.columns.tolist())

(99441, 12)
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'delivery_days', 'delivery_delay_days', 'is_late', 'order_month']

In [ ]:
from google.colab import files
import io
uploaded = files.upload()
Orders = pd.read_csv(io.BytesIO(uploaded[list(uploaded.keys())[0]]))
Orders.head()

Saving clean_Payments.csv to clean_Payments.csv

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [ ]:
from google.colab import files
import io
uploaded = files.upload()
Payments = pd.read_csv(io.BytesIO(uploaded[list(uploaded.keys())[0]]))
Payments.head()

Saving clean_Products.csv to clean_Products.csv

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [ ]:
Payments['product_name_lenght'] = Payments['product_name_lenght'].round().astype(int)
Payments['product_description_lenght'] = Payments['product_description_lenght'].round().astype(int)
Payments['product_photos_qty'] = Payments['product_photos_qty'].round().astype(int)

In [ ]:
Payments.to_csv('clean_Products.csv', index=False)

In [ ]:
from google.colab import files
import io
uploaded = files.upload()
Reviews = pd.read_csv(io.BytesIO(uploaded[list(uploaded.keys())[0]]))
Reviews.head()

Saving clean_Reviews.csv to clean_Reviews.csv

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [ ]:
Reviews['review_id'].duplicated().sum()

np.int64(814)

In [ ]:
dup_reviews = Reviews[Reviews['review_id'].duplicated(keep=False)].sort_values('review_id')
print(dup_reviews.shape)

(1603, 7)

In [ ]:
print(dup_reviews.groupby('review_id').size().value_counts())

2    764
3     25
Name: count, dtype: int64

In [ ]:
print(dup_reviews[dup_reviews.duplicated(keep=False)].shape)

(0, 7)

In [ ]:
dup_reviews = Reviews[Reviews['review_id'].duplicated(keep=False)]

print("Total duplicate rows:", dup_reviews.shape[0])
print("Exact duplicate rows:", dup_reviews.duplicated().sum())

Total duplicate rows: 1603
Exact duplicate rows: 0